version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/performance-lab
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      PHPFPM_HOST: wordpress
      PHPFPM_PORT: 9000
    depends_on:
      - wordpress
  wordpress:
    image: wordpress:performance
    build:
      context: ./wordpress
      args:
        - TIDEWAYS_VERSION=5.0.4
        - WPCLI_VERSION=2.5.0
    volumes:
      - wordpress:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/performance-lab
      - ../../vendor:/var/www/html/vendor
    environment:
      LIVE_PROFILER_CONNECTION_URL: mysql://root:password@db:3306/wordpress?charset=utf8
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        include 'vendor/autoload.php';

        // Don't start liveprof for CLI scripts.
        if ( php_sapi_name() != 'cli' ) {
          \Badoo\LiveProfiler\LiveProfiler::getInstance()
            ->setMode( \Badoo\LiveProfiler\LiveProfiler::MODE_DB )
            ->setDivider( 1 )
            ->useTidyWays()
            ->start();
        }

        $$memcached_servers = array( 'default' => array( 'memcached:11211' ) );
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql:/var/lib/mysql
      - ../../vendor/badoo/liveprof/bin/install_data/pdo_mysql/source.sql:/docker-entrypoint-initdb.d/01-install-liveprof-tables.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
  memcached:
    image: memcached:alpine
  liveprofui:
    image: liveprof-ui
    build:
      context: ./liveprof-ui
      args:
        - LIVEPROFUI_VERSION=1.2.19
    ports:
      - 8082:80
volumes:
  wordpress:
  mysql:
