name: Coding Standards

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if JavaScript-related files changed.
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.js'
      # This file configures JSHint. Changes could affect the outcome.
      - '.jshintrc'
  pull_request:
    branches:
      - trunk
      - 'release/**'
      - 'feature/**'
    # Only run if JavaScript-related files changed.
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.js'
      # This file configures JSHint. Changes could affect the outcome.
      - '.jshintrc'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  # Runs the JavaScript coding standards checks.
  #
  # JSHint violations are not currently reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the GitHub Action runner.
  # - Installs NodeJS.
  # - Logs updated debug information.
  # - Installs NPM dependencies.
  # - Run the WordPress JSHint checks.
  # - Ensures version-controlled files are not modified or deleted.
  jshint:
    name: JavaScript coding standards
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log debug information
        run: |
          npm --version
          node --version

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Log debug information
        run: |
          npm --version
          node --version

      - name: Install Dependencies
        run: npm ci

      - name: Run JSHint
        run: npm run grunt jshint

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
